apiVersion: v2
name: k8s-script-executor
description: A Helm chart for Kubernetes Script Executor
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: "Ade Adegboye"
    email: "alveocloudevops@gmail.com"
keywords:
  - kubernetes
  - script-executor
  - automation
home: "https://github.com/decloudz/k8s-script-executor"
sources:
  - "https://github.com/decloudz/k8s-script-executor" 