# Chart Releaser Configuration
# This file configures the chart-releaser action

# The GitHub repository to use
repository: alvdevcl/k8s-script-executor

# The GitHub Pages branch to use
pages_branch: gh-pages

# The directory containing the Helm charts
charts_dir: deploy/chart

# Whether to create a pull request instead of pushing directly
pr: false

# Whether to push changes to the GitHub Pages branch
push: true

# Whether to mark the latest release as 'latest'
make_release_latest: true

# Whether to host package files in the GitHub Pages branch
packages_with_index: true

# The template for release names
release_name_template: "{{ .Name }}-{{ .Version }}"

# The file containing release notes
release_notes_file: CHANGELOG.md

# Whether to skip existing releases
skip_existing: false

# Whether to generate release notes
generate_release_notes: true

# The remote to use when creating a local worktree
remote: origin

# The package path for chart packages
package_path: .cr-release-packages 