apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-script-executor.fullname" . }}-config
  labels:
    {{- include "k8s-script-executor.labels" . | nindent 4 }}
data:
  scripts.json: |
    {{- toJson .Values.config.scripts | nindent 4 }} 