{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-script-executor.fullname" . }}-role
  labels:
    {{- include "k8s-script-executor.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-script-executor.fullname" . }}-rolebinding
  labels:
    {{- include "k8s-script-executor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-script-executor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "k8s-script-executor.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }} 