apiVersion: v1
kind: ConfigMap
metadata:
  name: exec-operator-config
data:
  scripts.json: |
    [
      {
        "name": "where am i",
        "command": "pwd"
      },
      {
        "name": "list home directory",
        "command": "ls -al /home"
      }
    ]
