apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-script-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-script-executor
  template:
    metadata:
      labels:
        app: k8s-script-executor
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
      - name: server
        image: ghcr.io/decloudz/k8s-script-executor@sha256:82eb4d889cf980775105c37cccf3e472eb8d79fe48047bc84270a03d2a071f89
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: "prime-cloud"
        - name: SCRIPTS_JSON_PATH
          value: "/scripts/scripts.json"
        - name: POD_LABEL
          value: "app=query-server"  # Can be overridden by API request
        volumeMounts:
        - name: scripts-config
          mountPath: /scripts
      volumes:
      - name: scripts-config
        configMap:
          name: exec-operator-config
