apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-script-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-script-executor
  template:
    metadata:
      labels:
        app: k8s-script-executor
    spec:
      imagePullSecrets:
        - name: ghcr-repo-login-secret
      containers:
      - name: server
        image: ghcr.io/decloudz/k8s-script-executor:sha-a7b7635
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: "prime-cloud"
        - name: SCRIPTS_PATH
          value: "/config/scripts.json"
        - name: POD_LABEL
          value: "app=query-server"  # Can be overridden by API request
        volumeMounts:
        - name: scripts-config
          mountPath: /config
      volumes:
      - name: scripts-config
        configMap:
          name: exec-operator-config
