apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-api
  namespace: ac-prime-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exec-api
  template:
    metadata:
      labels:
        app: exec-api
    spec:
      containers:
      - name: api-server
        image: your-docker-repo/exec-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: "ac-prime-service-dev"
        - name: SCRIPTS_JSON_PATH
          value: "/scripts/scripts.json"
        - name: POD_LABEL
          value: "app=query-server"  # Can be overridden by API request
        volumeMounts:
        - name: scripts-config
          mountPath: /scripts
      volumes:
      - name: scripts-config
        configMap:
          name: exec-operator-config
