apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-script-executor
  namespace: prime-edm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-script-executor
  template:
    metadata:
      labels:
        app: k8s-script-executor
    spec:
      imagePullSecrets:
        - name: ghcr-repo-login-secret
      containers:
      - name: server
        image: ghcr.io/decloudz/k8s-script-executor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: "prime-cloud"
        - name: SCRIPTS_PATH
          value: "/config/scripts.json"
        - name: POD_LABEL_SELECTOR
          value: "app=prime-query-server"
        - name: PROCESS_TRACKING_SERVICE_URL
          value: "https://prime-edm.apps.rosa.pcs.iej5.p3.openshiftapps.com/process-tracking/api/v1/process"
        - name: PROCESS_TRACKING_STAGE
          value: "ENRICHMENT"
        - name: PROCESS_TRACKING_GROUP
          value: "test"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: scripts-config
          mountPath: /config
          readOnly: true
      serviceAccountName: exec-sa
      serviceAccount: exec-sa
      volumes:
      - name: scripts-config
        configMap:
          name: exec-operator-config
