apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: pod-exec-role
rules:
 - apiGroups: [""]
   resources: ["pods", "pods/exec", "configmaps"]
   verbs: ["create", "get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-binding
subjects:
  - kind: ServiceAccount
    name: exec-sa
    namespace: ac-prime-service-dev
roleRef:
  kind: Role
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exec-sa
