apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec-role
rules:
  # Permissions needed to find the target pod
  - apiGroups: [""] # Core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  # Permission needed to execute commands in the pod
  - apiGroups: [""] # Core API group
    resources: ["pods/exec"]
    verbs: ["create"]
  # Permission needed for the startup health check
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectaccessreviews"]
    verbs: ["create"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-binding
subjects:
  - kind: ServiceAccount
    name: exec-sa
    namespace: prime-edm
roleRef:
  kind: Role
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exec-sa
