apiVersion: v1
kind: Service
metadata:
  name: k8s-script-executor
  namespace: prime-edm
spec:
  selector:
    app: k8s-script-executor
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
