apiVersion: v1
kind: Service
metadata:
  name: exec-api-service
  namespace: ac-prime-service-dev
spec:
  selector:
    app: exec-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
