name: Release Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Docker image tag
        id: get_tag
        run: |
          echo "image_tag=${{ github.event.workflow_run.outputs.image_tag }}" >> $GITHUB_OUTPUT

      - name: Update Chart version
        run: |
          cd deploy/chart
          # Extract version from the first tag (assuming it's the semantic version)
          VERSION=$(echo "${{ steps.get_tag.outputs.image_tag }}" | tr -d '[]' | cut -d',' -f1 | tr -d '"')
          # Update Chart.yaml version
          sed -i "s/^version: .*$/version: ${VERSION#v}/" Chart.yaml
          # Update appVersion
          sed -i "s/^appVersion: .*$/appVersion: ${VERSION#v}/" Chart.yaml

      - name: Package Helm Chart
        run: |
          cd deploy/chart
          helm package .

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config: deploy/chart/cr.yaml
          skip_packaging: true
          skip_existing: false
          mark_as_latest: true
          packages_with_index: true
          pages_branch: gh-pages
          push: true
          release_name_template: "{{ .Name }}-{{ .Version }}"
          release_notes_file: deploy/chart/CHANGELOG.md
 