name: Release Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Docker image tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "image_tag=1.0.0" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ github.event.workflow_run.outputs.image_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Debug Chart Directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository structure:"
          find . -type f -name "Chart.yaml" -o -name "*.yaml" | grep -v '.github'
          echo "Checking Chart.yaml file status:"
          if [ -f deploy/chart/Chart.yaml ]; then
            echo "Chart.yaml exists in deploy/chart/"
            stat deploy/chart/Chart.yaml
            cat deploy/chart/Chart.yaml
          else
            echo "Chart.yaml does NOT exist in deploy/chart/"
          fi

      - name: Package with Absolute Path
        run: |
          # Extract version from the first tag (assuming it's the semantic version)
          VERSION=$(echo "${{ steps.get_tag.outputs.image_tag }}" | tr -d '[]' | cut -d',' -f1 | tr -d '"')
          # If VERSION is empty, set a default version
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          
          # Only update version if Chart.yaml exists
          if [ -f deploy/chart/Chart.yaml ]; then
            echo "Updating version in existing Chart.yaml"
            sed -i "s/^version:.*$/version: ${VERSION#v}/" deploy/chart/Chart.yaml
            sed -i "s/^appVersion:.*$/appVersion: ${VERSION#v}/" deploy/chart/Chart.yaml
          fi
          
          # Use absolute paths for Helm commands
          CHART_PATH="$(pwd)/deploy/chart"
          echo "Using absolute chart path: ${CHART_PATH}"
          echo "Chart directory contents:"
          ls -la "${CHART_PATH}"
          
          # Create temp packaging directory
          mkdir -p /tmp/helm-packages
          
          # Package using absolute path
          helm package "${CHART_PATH}" --destination /tmp/helm-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PACKAGE_PATH: /tmp/helm-packages
          CR_SKIP_EXISTING: "false"
        with:
          skip_packaging: true
 