name: Release Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Docker image tag
        id: get_tag
        run: |
          echo "image_tag=${{ github.event.workflow_run.outputs.image_tag }}" >> $GITHUB_OUTPUT

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Create Chart Directory Structure
        run: |
          mkdir -p /tmp/helm-chart/templates
          cp -r deploy/chart/templates/* /tmp/helm-chart/templates/
          cp deploy/chart/values.yaml /tmp/helm-chart/
          cp deploy/chart/.helmignore /tmp/helm-chart/
          cp deploy/chart/CHANGELOG.md /tmp/helm-chart/
          cp deploy/chart/cr.yaml /tmp/helm-chart/

      - name: Create Chart.yaml
        working-directory: /tmp/helm-chart
        run: |
          # Extract version from the first tag (assuming it's the semantic version)
          VERSION=$(echo "${{ steps.get_tag.outputs.image_tag }}" | tr -d '[]' | cut -d',' -f1 | tr -d '"')
          # If VERSION is empty, set a default version
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          # Create Chart.yaml with the updated version
          echo "apiVersion: v2" > Chart.yaml
          echo "name: k8s-script-executor" >> Chart.yaml
          echo "description: A Helm chart for Kubernetes Script Executor" >> Chart.yaml
          echo "type: application" >> Chart.yaml
          echo "version: ${VERSION#v}" >> Chart.yaml
          echo "appVersion: ${VERSION#v}" >> Chart.yaml
          echo "maintainers:" >> Chart.yaml
          echo "  - name: \"Ade Adegboye\"" >> Chart.yaml
          echo "    email: \"alveocloudevops@gmail.com\"" >> Chart.yaml
          echo "keywords:" >> Chart.yaml
          echo "  - kubernetes" >> Chart.yaml
          echo "  - script-executor" >> Chart.yaml
          echo "  - automation" >> Chart.yaml
          echo "home: \"https://github.com/alvdevcl/k8s-script-executor\"" >> Chart.yaml
          echo "sources:" >> Chart.yaml
          echo "  - \"https://github.com/alvdevcl/k8s-script-executor\"" >> Chart.yaml

      - name: Verify Chart Directory
        run: |
          ls -la /tmp/helm-chart/
          cat /tmp/helm-chart/Chart.yaml

      - name: Package Helm Chart
        working-directory: /tmp/helm-chart
        run: |
          helm dependency update
          helm package .
          mkdir -p /tmp/helm-packages
          mv *.tgz /tmp/helm-packages/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PACKAGE_PATH: /tmp/helm-packages
          CR_SKIP_EXISTING: "false"
        with:
          charts_dir: /tmp/helm-chart
          skip_packaging: true
 