name: Release Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Docker image tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "image_tag=1.0.0" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ github.event.workflow_run.outputs.image_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Fix Chart.yaml and Package
        run: |
          # Extract version from tag
          VERSION=$(echo "${{ steps.get_tag.outputs.image_tag }}" | tr -d '[]' | cut -d',' -f1 | tr -d '"')
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          
          # Ensure correct line endings
          cd deploy/chart
          dos2unix Chart.yaml || true
          
          # Check file permissions
          chmod 644 Chart.yaml
          
          # Fix Chart.yaml with minimal changes
          awk 'NR==1{print "apiVersion: v2"}
               NR==2{print "name: k8s-script-executor"}
               NR==3{print "description: A Helm chart for Kubernetes Script Executor"}
               NR==4{print "type: application"}
               NR==5{print "version: '${VERSION#v}'"}
               NR==6{print "appVersion: '${VERSION#v}'"}
               NR>6' Chart.yaml > Chart.yaml.new
          mv Chart.yaml.new Chart.yaml
          
          # Debug
          echo "Chart.yaml contents:"
          cat Chart.yaml
          
          # Package Chart
          helm lint .
          helm dependency update || true
          mkdir -p /tmp/helm-packages
          helm package . --destination /tmp/helm-packages
          
          # List packages
          echo "Generated packages:"
          ls -la /tmp/helm-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PACKAGE_PATH: /tmp/helm-packages
          CR_SKIP_EXISTING: "false"
        with:
          skip_packaging: true
 